// Package bootscript generates the custom boot.ipxe file that implements
// the 404-fallback-to-menu pattern for unknown machines.
//
// The generated script:
//  1. Attempts to chain to matchbox's /ipxe endpoint for MAC matching
//  2. If matchbox returns 404 (unknown MAC), falls through to a boot menu
//  3. The menu has a configurable timeout and auto-boots the default entry
package bootscript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/homelab/pxe-in-a-box/internal/config"
	"github.com/homelab/pxe-in-a-box/internal/matchbox"
)

// Endpoint describes the matchbox HTTP server address.
type Endpoint = matchbox.Endpoint

// Generate creates the boot.ipxe file from the menu config and matchbox endpoint.
// The file is written to the specified output path.
func Generate(menu *config.MenuConfig, assets *config.AssetsConfig, endpoint Endpoint, outputPath string) error {
	script := buildScript(menu, assets, endpoint)

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(script), 0644); err != nil {
		return fmt.Errorf("writing boot.ipxe: %w", err)
	}

	return nil
}

func buildScript(menu *config.MenuConfig, assets *config.AssetsConfig, endpoint Endpoint) string {
	var b strings.Builder

	baseURL := endpoint.BaseURL()
	timeoutMs := menu.Timeout * 1000

	// Header
	b.WriteString("#!ipxe\n")
	b.WriteString("# Generated by PXE-in-a-Box. Do not edit manually.\n")
	b.WriteString("# Attempts to match against known machines via matchbox.\n")
	b.WriteString("# If matchbox returns 404 (unknown MAC), falls through to boot menu.\n")
	b.WriteString("# Note: if a known machine's kernel boot fails, chain also falls through to menu.\n\n")

	// Chain attempt — matchbox returns 200 for known MACs, 404 for unknown
	b.WriteString(fmt.Sprintf("chain %s/ipxe?mac=${mac:hexhyp}&uuid=${uuid}&hostname=${hostname}&serial=${serial} || goto menu\n\n", baseURL))

	// Menu section
	b.WriteString(":menu\n")
	b.WriteString("menu PXE Boot Menu\n")
	for _, entry := range menu.Entries {
		b.WriteString(fmt.Sprintf("item %s %s\n", entry.ID, entry.Label))
	}
	b.WriteString(fmt.Sprintf("choose --default %s --timeout %d target && goto ${target}\n\n", menu.Default, timeoutMs))

	// Boot entries
	for _, entry := range menu.Entries {
		b.WriteString(fmt.Sprintf(":%s\n", entry.ID))

		info := assets.FindAsset(entry.Profile)
		if info == nil {
			// Should have been caught by validation, but guard against panics
			b.WriteString(fmt.Sprintf("echo Asset %q not found\n", entry.Profile))
			b.WriteString("goto menu\n\n")
			continue
		}

		kernel, initrd := bootPaths(info)

		// Build kernel args based on OS type
		args := buildKernelArgs(info, entry)

		b.WriteString(fmt.Sprintf("kernel %s %s\n", kernel, strings.Join(args, " ")))
		b.WriteString(fmt.Sprintf("initrd %s\n", initrd))
		b.WriteString("boot\n\n")
	}

	return b.String()
}

func bootPaths(info *config.AssetInfo) (kernel, initrd string) {
	base := fmt.Sprintf("/assets/%s/%s", info.ID, info.Arch)

	switch info.OSType {
	case config.OSTypeTalos:
		return fmt.Sprintf("%s/vmlinuz", base), fmt.Sprintf("%s/initramfs.xz", base)
	case config.OSTypeUbuntu:
		return fmt.Sprintf("%s/linux", base), fmt.Sprintf("%s/initrd", base)
	case config.OSTypeDebian:
		return fmt.Sprintf("%s/linux", base), fmt.Sprintf("%s/initrd.gz", base)
	case config.OSTypeArch:
		return fmt.Sprintf("%s/vmlinuz-linux", base), fmt.Sprintf("%s/initramfs-linux.img", base)
	default:
		return base + "/unknown-kernel", base + "/unknown-initrd"
	}
}

// buildKernelArgs returns the kernel arguments for a menu entry.
// For Talos maintenance mode, uses talos.config=null (no cluster join).
// For Talos with a config, uses talos.platform=metal.
// For other OSes, uses minimal boot args.
func buildKernelArgs(info *config.AssetInfo, entry config.MenuEntry) []string {
	switch info.OSType {
	case config.OSTypeTalos:
		// Menu entries for unknown machines always boot to maintenance mode
		// unless explicitly configured otherwise. We use talos.config=null
		// which puts Talos into maintenance mode (no cluster join).
		return []string{
			"initrd=initramfs.xz",
			"talos.platform=metal",
			"talos.config=null",
			"console=tty0",
			"printk.devkmsg=on",
		}
	case config.OSTypeUbuntu:
		return []string{
			"initrd=initrd",
			"root=/dev/ram0",
			"ramdisk_size=1500000",
			"ip=dhcp",
		}
	case config.OSTypeDebian:
		return []string{
			"initrd=initrd.gz",
		}
	default:
		return nil
	}
}
